# HOW TO USE THE COMPOSE FILE:
#
# Start
#   docker compose up dev_db        (Starts only the dev db)
#   docker compose up -d            (Starts all containers in the background)
#
# Stop
#   docker compose down             (Stops all containers)
#   docker compose down -v          (Stops all containers and nukes the local db)
#
#
networks:
  tero-network:

services:

  # Pgadmin web UI
  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: tero-pgadmin
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tero.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/pgadmin-servers.json:/pgadmin4/servers.json
    networks:
      - tero-network
    depends_on:
      - terodb

  # Local database    
  terodb:
    image: postgres:17
    container_name: terodb
    restart: unless-stopped
    ports:
    - "4000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tero-network

volumes:
  postgres-data:
  pgadmin-data: