[server]
address = "127.0.0.1"
port = 3000
gs_domain = "http://localhost:9000/"
page_size = 20
# database_url
# environment

[auth0]
# webhook_key
domain = "https://dev-tero.eu.auth0.com/"
audience = "https://api.tero.com"
