[server]
address = "127.0.0.1"
port = 3000
session_domain = "http://localhost:9000/"
page_size = 20
# database_url
# environment

[auth0]
# webhook_key
domain = "https://dev-8gif55bqfum82z1v.us.auth0.com/"
audience = "https://api.tero.com/"
